[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "urdr"
version = "0.1.0"
description = "Window-aware evolution of the time-series EACF method"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Martin B. Nielsen" }]
dependencies = [
    "mimir-astro @ git+https://github.com/nielsenmb/Mimir.git@880d23ce7562305d854142384513d7c1fb65661a",
    "numpy>=1.26",
    "scipy>=1.11",
]

[project.scripts]
urdr-tess-grid = "urdr.science:main"

[project.optional-dependencies]
test = [
    "matplotlib>=3.6",
    "pydocstyle>=6.3",
    "pytest>=7",
    "pytest-cov>=4",
]

[tool.hatch.build.targets.wheel]
packages = ["src/urdr"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.pydocstyle]
convention = "numpy"
